version: "3"
services:
  dicegamemongodb:
    image: mongo:latest
    container_name: "dicegamemongodb"
    ports:
      - "27017:27017"
  dice-game:
    image: dice-game:0.0.1
    container_name: "dice-game"
    ports:
      - "8080:8080"
    links:
      - dicegamemongodb
